#Command to run: typos -w --locale en-us

[default.extend-identifiers]
Behaviour = "Behaviour"
Behaviours = "Behaviours"
ret = "ret"

[default.extend-words]
Behaviour = "Behaviour"
Behaviours = "Behaviours"
ret = "ret"

[files]
# Ignore meta files
extend-exclude = ["*.meta", "Assets/Thirdparty/*"]
